### ISSUE TITLE
Mapa

### ISSUE THREAD

**Issue by Chris-628** [patrikcze/meshtatic_py#26]
U generování mapy prosím do rohu datum a čas vygenerování. 
Co se stane pokud node zmizí? Vypne se. Lze nastavit, že nody co sou hluchý více jak 24h a jejich případné routy budou buď jinou barvou (světle červená) nebo zmizí? Nebo červená šrafovaná čára.

**Comment by patrikcze** [comment]
Change active cutoff to whatever you need.
# Define the cutoff for "active" nodes (last 1 days)
active_cutoff = datetime.now() - timedelta(days=1)

**Comment by patrikcze** [comment]
Líp to asi nesvedu :-) 

<img width="1575" alt="image" src="https://github.com/user-attachments/assets/6f13fe27-1384-4666-a6c5-1c24893c57d0">
